name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild -t:restore

    - name: Build project
      run: msbuild "Oculus VR Dash Manager\Oculus VR Dash Manager.csproj" /p:Configuration=Release

    - name: Package build artifacts
      run: |
            mkdir $(Build.ArtifactStagingDirectory)
            cp "Oculus VR Dash Manager\bin\Release\*" $(Build.ArtifactStagingDirectory)
            cd $(Build.ArtifactStagingDirectory)
            Compress-Archive -Path * -DestinationPath $(Build.ArtifactStagingDirectory)/artifacts.zip
      shell: pwsh

    - name: List files in artifact staging directory
      run: ls -la $(Build.ArtifactStagingDirectory)
      shell: bash

    - name: Upload Build Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $(Build.ArtifactStagingDirectory)/artifacts.zip
        asset_name: Oculus VR Dash Manager.zip
        asset_content_type: application/zip
